meta_product_name: "Flock"
meta_title: "Flock - Walk together and stay safe."
meta_description: "Buddy up with women walking a similar journey to stay safe. Never walk alone again!"
meta_image: "cover.png" # should exist in `app/assets/images/`
